version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14-bullseye
    init: true
    hostname: app
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - $HOME/.aws/credentials:/home/node/.aws/credentials:ro
      - $HOME/.aws/config:/home/node/.aws/config:ro
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
